### ISSUE TITLE
go-client: Required Tag for property does not function correctly

### ISSUE THREAD

**Issue by alexthemayers** [SasSwart/gin-in-a-can#72]
```
                  domains:
                    type: array
                    required: [domain]
                    items:
                      type: object
                      required: [name, enabled]
                      properties:
                        explicit_domain_id:
                          type: string
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        enabled:
                          type: boolean
```

An open api definition such as this does not cause the generated code to omit the `omitempty` json tag for the domain, name, and enabled fields in the generated structs.
